// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.0
// source: articler.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ArticlerServiceClient is the client API for ArticlerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticlerServiceClient interface {
	SayHello(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type articlerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticlerServiceClient(cc grpc.ClientConnInterface) ArticlerServiceClient {
	return &articlerServiceClient{cc}
}

func (c *articlerServiceClient) SayHello(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/ArticlerService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticlerServiceServer is the server API for ArticlerService service.
// All implementations must embed UnimplementedArticlerServiceServer
// for forward compatibility
type ArticlerServiceServer interface {
	SayHello(context.Context, *Message) (*Message, error)
	mustEmbedUnimplementedArticlerServiceServer()
}

// UnimplementedArticlerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedArticlerServiceServer struct {
}

func (UnimplementedArticlerServiceServer) SayHello(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedArticlerServiceServer) mustEmbedUnimplementedArticlerServiceServer() {}

// UnsafeArticlerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticlerServiceServer will
// result in compilation errors.
type UnsafeArticlerServiceServer interface {
	mustEmbedUnimplementedArticlerServiceServer()
}

func RegisterArticlerServiceServer(s grpc.ServiceRegistrar, srv ArticlerServiceServer) {
	s.RegisterService(&ArticlerService_ServiceDesc, srv)
}

func _ArticlerService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticlerServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ArticlerService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticlerServiceServer).SayHello(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticlerService_ServiceDesc is the grpc.ServiceDesc for ArticlerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticlerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ArticlerService",
	HandlerType: (*ArticlerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _ArticlerService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "articler.proto",
}
